export const DISPLAY_ALERT = 'DISPLAY_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'

export const HIDE_WELCOME = 'HIDE_WELCOME'

export const SET_INITIAL_DEAL = 'SET_INITIAL_DEAL'


export const SETUP_GAME = 'SETUP_GAME'

export const INITIAL_DEAL_BEGIN = 'INITIAL_DEAL_BEGIN'
export const INITIAL_DEAL_SUCCESS= 'INITIAL_DEAL_SUCCESS'

export const CHECK_BLACKJACK_BEGIN = 'CHECK_BLACKJACK_BEGIN'
export const SET_PLAYER_BLACKJACK = 'SET_PLAYER_BLACKJACK'
export const SET_DEALER_BLACKJACK = 'SET_ DEALER_BLACKJACK'
export const CHECK_BLACKJACK_SUCCESS = 'CHECK_BLACKJACK_SUCCESS'

export const HANDLE_BOTH_BLACKJACK = 'HANDLE_BOTH_BLACKJACK'
export const HANDLE_PLAYER_BLACKJACK = 'HANDLE_PLAYER_BLACKJACK'
export const HANDLE_DEALER_BLACKJACK = 'HANDLE_DEALER_BLACKJACK'
export const HANDLE_NO_BLACKJACK = 'HANDLE_NO_BLACKJACK'

export const DISPLAY_OPTIONS_ALL = 'DISPLAY_OPTIONS_ALL'
export const DISPLAY_OPTIONS_DOUBLE = 'DISPLAY_OPTIONS_DOUBLE'
export const DISPLAY_OPTIONS_NORMAL = 'DISPLAY_OPTIONS_NORMAL'

export const PLAYER_BUST = 'PLAYER_BUST'

export const PLAYER_HIT = 'PLAYER_HIT'
export const PLAYER_STAY = 'PLAYER_STAY'
export const PLAYER_SPLIT = 'PLAYER_SPLIT'
export const PLAYER_DOUBLE = 'PLAYER_DOUBLE'

export const DEALER_BUST = 'DEALER_BUST'
export const DEALER_HIT = 'DEALER_HIT'
export const DEALER_STAY = 'DEALER_STAY'

export const PLAYER_WIN = 'PLAYER_WIN'
export const DEALER_WIN = 'DEALER_WIN'
export const PUSH = 'PUSH'

export const NEW_DEAL = 'NEW_DEAL'

export const CLEAR_HANDS = 'CLEAR_HANDS'